settings:
  digits: 3
  itemformat: markdown
  parent: ef_TA
  prefix: ef_TE
  sep: '-'
attributes:
  defaults:
    doc:
      title: "Eclipse Foundation Trustable Evidence"
      name: "Eclipse Foundation Trustable Evidence (ef_TE)"
      ref: "ef_TE"
  publish:
    - report