settings:
  digits: 3
  itemformat: markdown
  parent: TT
  prefix: up_TA
  sep: '-'
attributes:
  defaults:
    doc:
      title: "uProtocol Trustable Assertions"
      name: "uProtocol Trustable Assertions (up_TA)"
      ref: "up_TA"
  publish:
    - report