settings:
  digits: 2
  itemformat: markdown
  parent: TT
  prefix: ef_TA
  sep: '-'
attributes:
  defaults:
    doc:
      title: "Eclipse Foundation-related Trustable Assertions"
      name: "Eclipse Foundation-related Trustable Assertions (ef_TA)"
      ref: "ef_TA"
  publish:
    - report