settings:
  digits: 3
  itemformat: markdown
  parent: TT
  prefix: up_gen_TA
  sep: '-'
attributes:
  defaults:
    doc:
      title: "uProtocol Trustable Assertions (template)"
      name: "uProtocol Trustable Assertions (up_gen_TA)"
      ref: "up_gen_TA"
  publish:
    - report