settings:
  digits: 2
  itemformat: markdown
  parent: rst_TA
  prefix: rst_TE
  sep: '-'
attributes:
  defaults:
    doc:
      title: "Rust-related Trustable Evidence"
      name: "Rust-related Trustable Evidence (rst_TE)"
      ref: "rst_TE"
  publish:
    - report