settings:
  digits: 3
  itemformat: markdown
  parent: up_TA
  prefix: up_TE
  sep: '-'
attributes:
  defaults:
    doc:
      title: "uProtocol Trustable Evidence"
      name: "uProtocol Trustable Evidence (up_TE)"
      ref: "up_TE"
  publish:
    - report