settings:
  digits: 3
  itemformat: markdown
  parent: up_TA
  prefix: up-spec_TE
  sep: '-'
attributes:
  defaults:
    doc:
      title: "up-spec Trustable Evidence"
      name: "up-spec Trustable Evidence (up-spec_TE)"
      ref: "up-spec_TE"
  publish:
    - report