settings:
  digits: 2
  itemformat: markdown
  parent: TT
  prefix: TA
  sep: '-'
attributes:
  defaults:
    doc:
      title: "Trustable Assertions"
      name: "Trustable Assertions (TA)"
      ref: "TA"
  publish:
    - report
